version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8080:8000"
    environment:
      - AZURE_API_KEY= # Make sure to pass your API key
    volumes:
      - .:/app
    restart: unless-stopped
