version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8080:8000"
    environment:
      - AZURE_API_KEY=ff1cd87da4ba4304986e9bf652498906 # Make sure to pass your API key
    volumes:
      - .:/app
    restart: unless-stopped
